CREATE TABLE transactions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    last_edited_by_user_id BIGINT UNSIGNED NULL,
    transaction_type ENUM('income', 'expense') NOT NULL,
    transaction_date DATE NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    payee VARCHAR(255) NOT NULL,
    notes TEXT NULL,
    is_reviewed TINYINT(1) NOT NULL DEFAULT 0,
    exclude_from_budget TINYINT(1) NOT NULL DEFAULT 0,
    exclude_from_reports TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    KEY idx_transactions_household (household_id),
    KEY idx_transactions_account (account_id),
    KEY idx_transactions_category (category_id),
    KEY idx_transactions_date (transaction_date),
    CONSTRAINT fk_transactions_household FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_transactions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_transactions_last_edited_by FOREIGN KEY (last_edited_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
