CREATE TABLE recurring_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(150) NOT NULL,
    recurring_type ENUM('income', 'expense') NOT NULL,
    expected_amount DECIMAL(12,2) NOT NULL,
    frequency ENUM('weekly', 'biweekly', 'monthly', 'quarterly', 'annually') NOT NULL,
    next_due_date DATE NOT NULL,
    auto_pay TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active', 'canceled') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    canceled_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    KEY idx_recurring_items_household (household_id),
    KEY idx_recurring_items_due (next_due_date),
    CONSTRAINT fk_recurring_items_household FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_recurring_items_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_recurring_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_recurring_items_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
